- name: Configure MISO
  hosts: misoservers
  become: true
  tasks:
    - name: install mysql-server
      apt: name=mysql-server  install_recommends=no

    - name: install python-mysqldb
      apt: name=python-mysqldb  install_recommends=no

    - name: Start the MySQL service
      action: service name=mysql state=started

    - mysql_db: name=miso state=present collation=utf8_general_ci encoding=utf8

    - mysql_user: name=misouser host="%" password=12345 priv=miso.*:ALL state=present

    - name: Restart the MySQL service
      action: service name=mysql state=restarted enabled=true

    - name: Download flyway
      maven_artifact: >
        group_id=org.flywaydb
        artifact_id=flyway-commandline
        version=4.0.1
        extension=tar.gz
        dest=/home

    - name: Untar flyway
      unarchive: src=/home/flyway-commandline-4.0.1.tar.gz dest=/home remote_src=yes
 
    - name: Create symlink to flyway
      file: src=/home/flyway-4.0.1 dest=/home/flyway state=link

    - name: copy MISO db config file
      copy: src=files/ROOT.xml dest=/etc/tomcat8/Catalina/localhost/ROOT.xml

    - name: copy Tomcat config file
      copy: src=files/tomcat8 dest=/etc/default/tomcat8

    - name: Make MISO storage directory
      file: >
        path=/storage/miso
        state=directory
        owner=tomcat8
        group=tomcat8
        mode=0755

    - name: Download and untar MISO properties
      unarchive: >
        src=files/miso_userspace_properties.tar.gz
        dest=/storage/miso
        owner=tomcat8
        group=tomcat8
        mode=0755

    - name: download jndi-file-factory
      get_url: >
        url=http://hasbanana.co.uk/maven/repo/uk/ac/ebi/fgpt/jndi-file-factory/1.0/jndi-file-factory-1.0.jar
        dest=/var/lib/tomcat8/lib/
        owner=tomcat8
        group=tomcat8
        mode=0444

    - name: download mysql-connector-java
      maven_artifact: >
        group_id=mysql
        artifact_id=mysql-connector-java
        version=5.1.38
        dest=/var/lib/tomcat8/lib/

    - name: Change mysql-connector-java ownership
      file: >
        path=/var/lib/tomcat8/lib/mysql-connector-java-5.1.38.jar
        owner=tomcat8
        group=tomcat8
        mode=0444

    - name: copy flyway runner
      copy: >
        src=files/miso-install.sh
        dest=/home/

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: restart nginx
      service: name=nginx state=restarted
